// react/src/provider.tsx
import React, { createContext, useContext } from 'react'

export type RouteConfig = {
    login: string
    auth: string
    logout: string
}
export const routeConfig: RouteConfig = {
    login: '/api/hellocoop?op=login',
    auth: '/api/hellocoop?op=auth',
    logout: '/api/hellocoop?op=logout',
}

const HelloContext = createContext(undefined)

const HelloProvider = ({ children, auth, config} : any) => { //TBD any
    if (config?.login) routeConfig.login = config.login 
    if (config?.auth) routeConfig.auth = config.auth 
    if (config?.logout) routeConfig.logout = config.logout 
    return (
      <HelloContext.Provider value={auth}>
          {children}
      </HelloContext.Provider>
    )
}

const useHelloProviderContext = () => {
    return useContext(HelloContext)
};

export { HelloProvider, useHelloProviderContext }

// svelte/src/Provider.svelte
<script context="module">
  import { setContext, getContext, onMount } from 'svelte'
  
  export const routeConfig = {
      login: '/api/hellocoop?login=true',
      auth: '/api/hellocoop?auth=true',
      logout: '/api/hellocoop?logout=true',
  }
  
  export const getHelloProviderContext = () => {
      return getContext('HelloProviderContext')
  }
</script>
    
<script>
    export let auth = {}
    export let config = {}

    setContext('HelloProviderContext', auth)

    if (config?.login) routeConfig.login = config.login 
    if (config?.auth) routeConfig.auth = config.auth 
    if (config?.logout) routeConfig.logout = config.logout 
</script>
    
<slot/>
