// svelte/src/buttons/BaseButton.svelte
<script lang="ts">
  import { routeConfig } from "./hello.config"
  import { Button, type ProviderHint, type Scope } from '@hellocoop/types'

  interface $$Props {
    label?: string
    style?: any
    color?: Button.Color
    theme?: Button.Theme
    hover?: Button.Hover
    scope?: Scope[]
    updateScope?: Button.UpdateScope
    targetURI?: string
    providerHint?: ProviderHint[],
    showLoader?: boolean,
    disabled?: boolean
  }

  // All prop exports must still be typed standalone and in the $$Props interface
  export let label: string = "ō&nbsp;&nbsp;&nbsp;Continue with Hellō";
  export let style: any = {} //TBD any
  export let color: Button.Color = "black"
  export let theme: Button.Theme = "ignore-light"
  export let hover: Button.Hover = "pop"
  export let scope: Scope[];
  export let updateScope: Button.UpdateScope;
  export let targetURI: string = ""
  export let providerHint: ProviderHint[];
  export let showLoader: boolean = false
  export let disabled: boolean = false

  let clicked: boolean = false
  const loginRoute = new URL(routeConfig.login, window.location.origin)
  if(scope)
    loginRoute.searchParams.set("scope", scope.join(" "))

  loginRoute.searchParams.set("target_uri", targetURI || window.location.pathname)
  
  if(updateScope)
      loginRoute.searchParams.set("scope", "profile_update " + updateScope)

  if(providerHint)
    loginRoute.searchParams.set("provider_hint", providerHint.join(" "))

  const onClickHandler = (): void => {
      clicked = true
      window.location.href = loginRoute.href
  }
</script>

<button
  on:click={onClickHandler}
  class="hello-btn {Button.CLASS_MAPPING[color]?.[theme]} {Button.HOVER_MAPPING[hover]}"
  class:hello-btn-loader={showLoader || clicked}
  disabled={disabled || clicked}
  {style}
>
  {@html label}
</button>

// vue/src/BaseButton.vue
<script setup lang="ts">
  import { ref } from 'vue'
  import { routeConfig } from "./hello.config"
  import { Button, type ProviderHint, type Scope } from '@hellocoop/types'
  
  const clicked = ref(false)

  export interface Props {
    label?: string
    style?: any
    color?: Button.Color
    theme?: Button.Theme
    hover?: Button.Hover
    scope?: Scope[]
    updateScope?: Button.UpdateScope
    targetURI?: string
    providerHint?: ProviderHint[]
    showLoader?: boolean
    disabled?: boolean
  }
  
  const props = withDefaults(defineProps<Props>(), {
    label: "ō&nbsp;&nbsp;&nbsp;Continue with Hellō",
    color: "black",
    theme: "ignore-light",
    hover: "pop",
    showLoader: false,
    disabled: false
  })

  const loginRoute = new URL(routeConfig.login, window.location.origin)

  if(props.scope)
    loginRoute.searchParams.set("scope", props.scope.join(" "))

  loginRoute.searchParams.set("target_uri", props.targetURI || window.location.pathname)
  
  if(props.updateScope)
      loginRoute.searchParams.set("scope", "profile_update " + props.updateScope)

  if(props.providerHint)
    loginRoute.searchParams.set("provider_hint", props.providerHint.join(" "))
  
  const onClickHandler = (): void => {
    clicked.value = true
    window.location.href = loginRoute.href
  }
</script>

<template>
  <button
    @click="onClickHandler"
    :class="['hello-btn', Button.CLASS_MAPPING[props.color]?.[props.theme], Button.HOVER_MAPPING[hover], (showLoader || clicked) && 'hello-btn-loader']"
    :disabled="props.disabled || clicked"
    :style="style"
  >
    <span v-html="label"></span>
  </button>
</template>
